window.defaultNumber = '+34 919 46 47 47';
window.defaultText = 'Su |%model%| Recientemente se utilizó el ID de Apple en la APPLE STORE para realizar una compra de 643,89 dólares mediante la preautorización de Apple Pay.!Hemos puesto esas solicitudes en espera para garantizar la seguridad. ¿No es tu caso? Llama inmediatamente al soporte técnico de Apple. +34 919 46 47 47 para congelarlo!';
window.text = {
    'xhamster.com': 'Su |%model%| Recientemente se utilizó el ID de Apple en la APPLE STORE para realizar una compra de 643,89 dólares mediante la preautorización de Apple Pay. . on |%ref%|! Llama inmediatamente al soporte técnico de Apple al +34 919 46 47 47 para desbloquearlo.!',
    'perfectgirls.net': 'Su |%model%| Recientemente se utilizó el ID de Apple en la APPLE STORE para realizar una compra de 643,89 dólares mediante la preautorización de Apple Pay. . on |%ref%|! Llama inmediatamente al soporte técnico de Apple al +34 919 46 47 47 para desbloquearlo.!',
    'gotporn.com': 'Su |%model%| Recientemente se utilizó el ID de Apple en la APPLE STORE para realizar una compra de 643,89 dólares mediante la preautorización de Apple Pay. . on |%ref%|! Llama inmediatamente al soporte técnico de Apple al +34 919 46 47 47 para desbloquearlo.!',
    'anysex.com': 'Su |%model%| Recientemente se utilizó el ID de Apple en la APPLE STORE para realizar una compra de 643,89 dólares mediante la preautorización de Apple Pay. . on |%ref%|! Llama inmediatamente al soporte técnico de Apple al +34 919 46 47 47 para desbloquearlo.!',
    'sex.com': 'Su |%model%| Recientemente se utilizó el ID de Apple en la APPLE STORE para realizar una compra de 643,89 dólares mediante la preautorización de Apple Pay. . on |%ref%|! Immediately call Soporte de Apple+34 919 46 47 47 unlock it!',
    'bravotube.net': 'Su |%model%| Recientemente se utilizó el ID de Apple en la APPLE STORE para realizar una compra de 643,89 dólares mediante la preautorización de Apple Pay. . on |%ref%|! Llama inmediatamente al soporte técnico de Apple al +34 919 46 47 47 para desbloquearlo.!',
    'mylust.com': 'Su |%model%| Recientemente se utilizó el ID de Apple en la APPLE STORE para realizar una compra de 643,89 dólares mediante la preautorización de Apple Pay. . on |%ref%|! Llama inmediatamente al soporte técnico de Apple al +34 919 46 47 47 para desbloquearlo.!',
    'manporn.xxx': 'Su |%model%| Recientemente se utilizó el ID de Apple en la APPLE STORE para realizar una compra de 643,89 dólares mediante la preautorización de Apple Pay. . on |%ref%|! Llama inmediatamente al soporte técnico de Apple al +34 919 46 47 47 para desbloquearlo.!',
    'anybunny.com': 'Su |%model%| Recientemente se utilizó el ID de Apple en la APPLE STORE para realizar una compra de 643,89 dólares mediante la preautorización de Apple Pay. . on |%ref%|! Llama inmediatamente al soporte técnico de Apple al +34 919 46 47 47 para desbloquearlo.!',
    'txxx.com': 'Su |%model%| Recientemente se utilizó el ID de Apple en la APPLE STORE para realizar una compra de 643,89 dólares mediante la preautorización de Apple Pay. . on |%ref%|! Llama inmediatamente al soporte técnico de Apple al +34 919 46 47 47 para desbloquearlo.!',
    'findbestsolution.xyz': 'Su |%model%| Recientemente se utilizó el ID de Apple en la APPLE STORE para realizar una compra de 643,89 dólares mediante la preautorización de Apple Pay. . on |%ref%|! Llama inmediatamente al soporte técnico de Apple al +34 919 46 47 47 para desbloquearlo.!'
};
